### ISSUE TITLE
Discussion for website color scheme. 

### ISSUE THREAD

**Issue by wimpywarlord** [vinnovateit/pondi_planner_front#1]
My suggestion for color scheme :  https://flatuicolors.com/palette/in

**Comment by ArpitKotecha** [comment]
https://uigradients.com/#FacebookMessenger

**Comment by wimpywarlord** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/41532804/85879434-fe54d900-b7f7-11ea-91d0-88ec626deef7.png)

Above is the color scheme for the website.
