### ISSUE TITLE
Add proper permissions and autobot for review.

### ISSUE THREAD

**Issue by wimpywarlord** [vinnovateit/pondi_planner_front#6]
Add automatic review from me and you for PR's and also block directly pushing into the master.

**Comment by Nirmitjatana** [comment]
@wimpywarlord Check this link to restrict people from directly pushing into the master
https://stackoverflow.com/questions/46146491/prevent-pushing-to-master-on-github

**Comment by Nirmitjatana** [comment]
Some automations we can add
Auto issue label
Github actions
Linting bot
Netlify build preview

**Comment by Nirmitjatana** [comment]
> Some automations we can add
> Auto issue label
> Github actions
> Linting bot
> Netlify build preview

@wimpywarlord @ArpitKotecha

**Comment by wimpywarlord** [comment]
Will have a look

**Comment by ArpitKotecha** [comment]
> Some automations we can add
> Auto issue label
> Github actions
> Linting bot
> Netlify build preview

Github actions for what specifically?
Will add netlify.
Adding linting bot will make development slower and harder since for most of them it's their first project. Will add from next one.

**Comment by ArpitKotecha** [comment]
@wimpywarlord Directly push to master blocked
